In [1]:
import os, json, shutil
from pathlib import Path
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm
from tqdm import tqdm
from glob import glob
import pandas as pd
from scipy.ndimage import label as cc_label


SPLITS_2020 = Path(r"D:\master_experiments\data\splits\BraTS2020_Splits")
SPLITS_2024 = Path(r"D:\master_experiments\data\splits\BraTS2024_Splits")

NNUNET_2020_BASE = Path(r"D:\master_experiments\models_configs\nnUNet_2020")
NNUNET_2024_BASE = Path(r"D:\master_experiments\models_configs\nnUNet_2024")

DATASET_2020_ID, DATASET_2020_NAME = 902, "BraTS2020_Baseline_4ch"
DATASET_2024_ID, DATASET_2024_NAME = 903, "BraTS2024_Baseline_4ch"

IMAGES_TS_2020 = NNUNET_2020_BASE / "nnUNet_raw" / f"Dataset{DATASET_2020_ID:03d}_{DATASET_2020_NAME}" / "imagesTs"
IMAGES_TS_2024 = NNUNET_2024_BASE / "nnUNet_raw" / f"Dataset{DATASET_2024_ID:03d}_{DATASET_2024_NAME}" / "imagesTs"

CROSS_BASE        = Path(r"D:\master_experiments\models_configs\cross_eval\nnUNet")
PRED_2020_ON_2024 = CROSS_BASE / "preds_2020_on_2024"
PRED_2024_ON_2020 = CROSS_BASE / "preds_2024_on_2020"
LOGS              = CROSS_BASE / "logs"
for p in [PRED_2020_ON_2024, PRED_2024_ON_2020, LOGS]:
    p.mkdir(parents=True, exist_ok=True)

print("Paths OK")
print(f"  imagesTs 2020 existe: {IMAGES_TS_2020.exists()}")
print(f"  imagesTs 2024 existe: {IMAGES_TS_2024.exists()}")
print(f"  Splits 2020 existe:  {SPLITS_2020.exists()}")
print(f"  Splits 2024 existe:  {SPLITS_2024.exists()}")

Paths OK
  imagesTs 2020 existe: True
  imagesTs 2024 existe: True
  Splits 2020 existe:  True
  Splits 2024 existe:  True

In [2]:
with open(SPLITS_2020 / "splits_metadata.json", "r", encoding="utf-8") as f:
    meta_2020 = json.load(f)
with open(SPLITS_2024 / "splits_metadata.json", "r", encoding="utf-8") as f:
    meta_2024 = json.load(f)

test_ids_2020 = meta_2020["ids"]["test"]
test_ids_2024 = meta_2024["ids"]["test"]

print(f"Test BraTS2020: {len(test_ids_2020)} casos")
print(f"Test BraTS2024: {len(test_ids_2024)} casos")

Test BraTS2020: 53 casos
Test BraTS2024: 203 casos

In [3]:
def case_dir_2020(cid): return SPLITS_2020 / "test" / cid
def case_dir_2024(cid): return SPLITS_2024 / "test" / cid

def find_seg(d):
    for cand in [d / "seg.nii.gz", d / "seg.nii"]:
        if cand.exists(): return cand
    cands = sorted(d.glob("*seg*.nii*"))
    if not cands:
        raise FileNotFoundError(f"seg nao encontrada em {d}")
    return cands[0]

def load_arr(p):
    return np.asanyarray(nib.load(str(p)).dataobj)

def dice(a, b):
    inter = np.count_nonzero(a & b)
    denom = np.count_nonzero(a) + np.count_nonzero(b)
    return 1.0 if denom == 0 else (2.0 * inter / denom)

def get_pred_path(pred_dir, cid):
    p = pred_dir / f"{cid}.nii.gz"
    if p.exists(): return p
    p = pred_dir / f"{cid}.nii"
    if p.exists(): return p
    raise FileNotFoundError(f"Pred nao encontrada: {pred_dir}/{cid}")

print("Helpers OK")

Helpers OK

In [4]:
# Direcao A: nnUNet treinado em BraTS2020 -> predito sobre teste BraTS2024 

os.environ["nnUNet_raw"]          = str(NNUNET_2020_BASE / "nnUNet_raw")
os.environ["nnUNet_preprocessed"] = str(NNUNET_2020_BASE / "nnUNet_preprocessed")
os.environ["nnUNet_results"]      = str(NNUNET_2020_BASE / "nnUNet_results")

!nnUNetv2_predict -i "{IMAGES_TS_2024}" -o "{PRED_2020_ON_2024}" -d {DATASET_2020_ID} -c 3d_fullres -f 0 -tr nnUNetTrainer_250epochs

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 203 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 203 cases that I would like to predict

Predicting BraTS-GLI-00005-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00005-100

Predicting BraTS-GLI-00008-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00008-101

Predicting BraTS-GLI-00020-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00020-100

Predicting BraTS-GLI-00027-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00027-100

Predicting BraTS-GLI-00063-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00063-101

Predicting BraTS-GLI-00078-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00078-100

Predicting BraTS-GLI-00483-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00483-100

Predicting BraTS-GLI-00498-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00498-100

Predicting BraTS-GLI-00511-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00511-100

Predicting BraTS-GLI-00511-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00511-101

Predicting BraTS-GLI-00518-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00518-101

Predicting BraTS-GLI-00529-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00529-100

Predicting BraTS-GLI-00548-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-00548-100

Predicting BraTS-GLI-02061-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02061-100

Predicting BraTS-GLI-02062-105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02062-105

Predicting BraTS-GLI-02063-105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02063-105

Predicting BraTS-GLI-02066-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02066-101

Predicting BraTS-GLI-02070-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02070-100

Predicting BraTS-GLI-02072-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02072-100

Predicting BraTS-GLI-02079-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02079-100

Predicting BraTS-GLI-02082-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02082-101

Predicting BraTS-GLI-02087-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02087-101

Predicting BraTS-GLI-02087-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02087-102

Predicting BraTS-GLI-02093-105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02093-105

Predicting BraTS-GLI-02096-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02096-100

Predicting BraTS-GLI-02096-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02096-102

Predicting BraTS-GLI-02101-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02101-100

Predicting BraTS-GLI-02103-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02103-102

Predicting BraTS-GLI-02103-105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02103-105

Predicting BraTS-GLI-02104-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02104-100

Predicting BraTS-GLI-02105-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02105-102

Predicting BraTS-GLI-02106-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02106-101

Predicting BraTS-GLI-02106-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02106-102

Predicting BraTS-GLI-02111-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02111-100

Predicting BraTS-GLI-02116-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02116-100

Predicting BraTS-GLI-02124-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02124-101

Predicting BraTS-GLI-02129-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02129-101

Predicting BraTS-GLI-02129-104:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02129-104

Predicting BraTS-GLI-02131-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02131-101

Predicting BraTS-GLI-02137-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02137-100

Predicting BraTS-GLI-02137-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02137-102

Predicting BraTS-GLI-02143-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02143-101

Predicting BraTS-GLI-02144-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02144-100

Predicting BraTS-GLI-02147-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02147-101

Predicting BraTS-GLI-02152-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02152-101

Predicting BraTS-GLI-02152-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02152-102

Predicting BraTS-GLI-02153-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02153-100

Predicting BraTS-GLI-02153-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02153-101

Predicting BraTS-GLI-02156-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02156-100

Predicting BraTS-GLI-02162-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02162-100

Predicting BraTS-GLI-02164-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02164-100

Predicting BraTS-GLI-02167-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02167-100

Predicting BraTS-GLI-02169-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02169-101

Predicting BraTS-GLI-02171-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02171-100

Predicting BraTS-GLI-02181-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02181-101

Predicting BraTS-GLI-02184-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02184-101

Predicting BraTS-GLI-02185-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02185-101

Predicting BraTS-GLI-02186-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02186-103

Predicting BraTS-GLI-02188-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02188-100

Predicting BraTS-GLI-02193-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02193-102

Predicting BraTS-GLI-02196-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02196-101

Predicting BraTS-GLI-02196-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02196-103

Predicting BraTS-GLI-02197-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02197-100

Predicting BraTS-GLI-02199-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02199-101

Predicting BraTS-GLI-02205-105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02205-105

Predicting BraTS-GLI-02208-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02208-100

Predicting BraTS-GLI-02208-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02208-102

Predicting BraTS-GLI-02209-104:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02209-104

Predicting BraTS-GLI-02215-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02215-101

Predicting BraTS-GLI-02216-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02216-103

Predicting BraTS-GLI-02217-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02217-101

Predicting BraTS-GLI-02218-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02218-101

Predicting BraTS-GLI-02218-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02218-102

Predicting BraTS-GLI-02220-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02220-100

Predicting BraTS-GLI-02221-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02221-101

Predicting BraTS-GLI-02221-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02221-103

Predicting BraTS-GLI-02225-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02225-101

Predicting BraTS-GLI-02227-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02227-101

Predicting BraTS-GLI-02236-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02236-102

Predicting BraTS-GLI-02236-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02236-103

Predicting BraTS-GLI-02238-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02238-103

Predicting BraTS-GLI-02248-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02248-100

Predicting BraTS-GLI-02248-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02248-102

Predicting BraTS-GLI-02248-104:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02248-104

Predicting BraTS-GLI-02249-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02249-101

Predicting BraTS-GLI-02254-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02254-100

Predicting BraTS-GLI-02268-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02268-100

Predicting BraTS-GLI-02278-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02278-100

Predicting BraTS-GLI-02284-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02284-100

Predicting BraTS-GLI-02285-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02285-103

Predicting BraTS-GLI-02289-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02289-101

Predicting BraTS-GLI-02302-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02302-100

Predicting BraTS-GLI-02335-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02335-101

Predicting BraTS-GLI-02338-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02338-100

Predicting BraTS-GLI-02342-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02342-100

Predicting BraTS-GLI-02352-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02352-100

Predicting BraTS-GLI-02378-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02378-100

Predicting BraTS-GLI-02388-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02388-101

Predicting BraTS-GLI-02518-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02518-101

Predicting BraTS-GLI-02520-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02520-100

Predicting BraTS-GLI-02520-103:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02520-103

Predicting BraTS-GLI-02547-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02547-101

Predicting BraTS-GLI-02548-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02548-100

Predicting BraTS-GLI-02548-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02548-101

Predicting BraTS-GLI-02548-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02548-102

Predicting BraTS-GLI-02549-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02549-101

Predicting BraTS-GLI-02598-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02598-101

Predicting BraTS-GLI-02608-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02608-101

Predicting BraTS-GLI-02609-102:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02609-102

Predicting BraTS-GLI-02623-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02623-100

Predicting BraTS-GLI-02625-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02625-100

Predicting BraTS-GLI-02633-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02633-100

Predicting BraTS-GLI-02634-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02634-100

Predicting BraTS-GLI-02636-100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02636-100

Predicting BraTS-GLI-02637-101:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS-GLI-02637-101

Predicting BraTS-GLI-02658-100:
perform_everything_on_device: True

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:01<00:11,  1.62s/it]
 25%|##5       | 2/8 [00:01<00:04,  1.29it/s]
 38%|###7      | 3/8 [00:02<00:02,  1.75it/s]
 50%|#####     | 4/8 [00:02<00:01,  2.10it/s]
 62%|######2   | 5/8 [00:02<00:01,  2.36it/s]
 75%|#######5  | 6/8 [00:03<00:00,  2.55it/s]
 88%|########7 | 7/8 [00:03<00:00,  2.69it/s]
100%|##########| 8/8 [00:03<00:00,  2.79it/s]
100%|##########| 8/8 [00:03<00:00,  2.12it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  5.35it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.82it/s]
 75%|#######5  | 3/4 [00:00<00:00,  3.40it/s]
100%|##########| 4/4 [00:01<00:00,  3.25it/s]
100%|##########| 4/4 [00:01<00:00,  3.44it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.43it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.70it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.35it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.27it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.18it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.08it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.07it/s]
100%|##########| 8/8 [00:02<00:00,  3.06it/s]
100%|##########| 8/8 [00:02<00:00,  3.20it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.60it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.35it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.15it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.10it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.07it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.10it/s]
100%|##########| 8/8 [00:02<00:00,  3.03it/s]
100%|##########| 8/8 [00:02<00:00,  3.18it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.55it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.28it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.12it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.09it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.08it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.02it/s]
100%|##########| 8/8 [00:02<00:00,  3.03it/s]
100%|##########| 8/8 [00:02<00:00,  3.16it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.53it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.39it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.19it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.13it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.05it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.05it/s]
100%|##########| 8/8 [00:02<00:00,  3.01it/s]
100%|##########| 8/8 [00:02<00:00,  3.17it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.37it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.54it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.22it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.14it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.05it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.95it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.90it/s]
100%|##########| 8/8 [00:02<00:00,  2.95it/s]
100%|##########| 8/8 [00:02<00:00,  3.08it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.63it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.76it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.39it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.23it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.16it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.11it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.08it/s]
100%|##########| 8/8 [00:02<00:00,  3.06it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.78it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.37it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.24it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.16it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.13it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.10it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.54it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.75it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.38it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.24it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.17it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.13it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.10it/s]
100%|##########| 8/8 [00:02<00:00,  3.08it/s]
100%|##########| 8/8 [00:02<00:00,  3.23it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.40it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.68it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.35it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.27it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.19it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.10it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.08it/s]
100%|##########| 8/8 [00:02<00:00,  3.07it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.47it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.71it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.37it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.22it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.14it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.10it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.12it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]
100%|##########| 8/8 [00:02<00:00,  3.20it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.44it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.73it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.39it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.24it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.17it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.12it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.08it/s]
100%|##########| 8/8 [00:02<00:00,  3.06it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.51it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.36it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.23it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.17it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.11it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.09it/s]
100%|##########| 8/8 [00:02<00:00,  3.07it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  5.44it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.69it/s]
 75%|#######5  | 3/4 [00:00<00:00,  3.34it/s]
100%|##########| 4/4 [00:01<00:00,  3.22it/s]
100%|##########| 4/4 [00:01<00:00,  3.40it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.63it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.38it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.24it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.18it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.07it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.07it/s]
100%|##########| 8/8 [00:02<00:00,  3.06it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.58it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.69it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.35it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.23it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.16it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.12it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.10it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]
100%|##########| 8/8 [00:02<00:00,  3.20it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.67it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.75it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.37it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.24it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.15it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.12it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.05it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]
100%|##########| 8/8 [00:02<00:00,  3.21it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  5.34it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.81it/s]
 75%|#######5  | 3/4 [00:00<00:00,  3.39it/s]
100%|##########| 4/4 [00:01<00:00,  3.25it/s]
100%|##########| 4/4 [00:01<00:00,  3.44it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.70it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.73it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.36it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.22it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.15it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.05it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.95it/s]
100%|##########| 8/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  3.11it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.98it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.28it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.10it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.02it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.98it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.95it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  2.99it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.33it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.55it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.22it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.14it/s]
 62%|######2   | 5/8 [00:01<00:01,  3.00it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.96it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.77it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]
100%|##########| 8/8 [00:02<00:00,  2.99it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.27it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.35it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.13it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.05it/s]
 62%|######2   | 5/8 [00:01<00:01,  3.00it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.96it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.95it/s]
100%|##########| 8/8 [00:02<00:00,  2.94it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.58it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.49it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.03it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.81it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.79it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.83it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  2.91it/s]
100%|##########| 8/8 [00:02<00:00,  2.96it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.59it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.72it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.31it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.17it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.15it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.11it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.08it/s]
100%|##########| 8/8 [00:02<00:00,  3.03it/s]
100%|##########| 8/8 [00:02<00:00,  3.18it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.32it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.68it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.36it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.23it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.16it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.12it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.10it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]
100%|##########| 8/8 [00:02<00:00,  3.20it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.61it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.60it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.25it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.17it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.12it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.10it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.03it/s]
100%|##########| 8/8 [00:02<00:00,  3.02it/s]
100%|##########| 8/8 [00:02<00:00,  3.16it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.48it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.73it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.31it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.13it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.05it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.91it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.86it/s]
100%|##########| 8/8 [00:02<00:00,  2.82it/s]
100%|##########| 8/8 [00:02<00:00,  3.03it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.90it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.19it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.11it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.13it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.09it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.07it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.00it/s]
100%|##########| 8/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.13it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.41it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.14it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.04it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.99it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.96it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.99it/s]
100%|##########| 8/8 [00:02<00:00,  2.92it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.93it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.47it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.19it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.01it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.93it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.88it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  2.99it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.95it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.50it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.20it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.07it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.02it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.94it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.98it/s]
100%|##########| 8/8 [00:02<00:00,  2.92it/s]
100%|##########| 8/8 [00:02<00:00,  3.05it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  5.29it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.67it/s]
 75%|#######5  | 3/4 [00:00<00:00,  3.27it/s]
100%|##########| 4/4 [00:01<00:00,  3.11it/s]
100%|##########| 4/4 [00:01<00:00,  3.30it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.23it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.52it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.19it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.11it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.03it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.04it/s]
 88%|########7 | 7/8 [00:02<00:00,  3.00it/s]
100%|##########| 8/8 [00:02<00:00,  2.98it/s]
100%|##########| 8/8 [00:02<00:00,  3.10it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.39it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.48it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.18it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.08it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.02it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.93it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  3.02it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  5.48it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.74it/s]
 75%|#######5  | 3/4 [00:00<00:00,  3.38it/s]
100%|##########| 4/4 [00:01<00:00,  3.13it/s]
100%|##########| 4/4 [00:01<00:00,  3.35it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.77it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.03it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.98it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.96it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.90it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  2.90it/s]
100%|##########| 8/8 [00:02<00:00,  2.99it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.95it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.21it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.85it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.78it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.82it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.86it/s]
100%|##########| 8/8 [00:02<00:00,  2.88it/s]
100%|##########| 8/8 [00:02<00:00,  2.93it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.90it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.30it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.76it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.81it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.83it/s]
100%|##########| 8/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  2.91it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.01it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.49it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.27it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.16it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.01it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.93it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.93it/s]
100%|##########| 8/8 [00:02<00:00,  2.88it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.09it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.62it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.26it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.10it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.97it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.87it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  2.85it/s]
100%|##########| 8/8 [00:02<00:00,  3.02it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.24it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.68it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.19it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.02it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.97it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.95it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.94it/s]
100%|##########| 8/8 [00:02<00:00,  2.88it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.90it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.36it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.12it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.03it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.04it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.91it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.90it/s]
100%|##########| 8/8 [00:02<00:00,  2.95it/s]
100%|##########| 8/8 [00:02<00:00,  3.04it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.89it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.36it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.07it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.85it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.84it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.90it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.94it/s]
100%|##########| 8/8 [00:02<00:00,  2.98it/s]
100%|##########| 8/8 [00:02<00:00,  3.01it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.00it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.28it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.10it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.03it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.98it/s]
 75%|#######5  | 6/8 [00:01<00:00,  2.90it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.96it/s]
100%|##########| 8/8 [00:02<00:00,  2.89it/s]
100%|##########| 8/8 [00:02<00:00,  3.01it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.68it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.74it/s]
 38%|###7      | 3/8 [00:00<00:01,  3.30it/s]
 50%|#####     | 4/8 [00:01<00:01,  3.19it/s]
 62%|######2   | 5/8 [00:01<00:00,  3.07it/s]
 75%|#######5  | 6/8 [00:01<00:00,  3.06it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.94it/s]
100%|##########| 8/8 [00:02<00:00,  2.95it/s]
100%|##########| 8/8 [00:02<00:00,  3.12it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

In [5]:
# Metrica 1 (A): Dice GLOBAL - modelo 2020 sobre teste 2024

rows = []
for cid in tqdm(test_ids_2024, desc="Dice global por caso (A: 2020->2024)"):
    gt = load_arr(find_seg(case_dir_2024(cid))).astype(np.int16)  
    pr = load_arr(get_pred_path(PRED_2020_ON_2024, cid)).astype(np.int16) 

    wt = dice(((gt==1)|(gt==2)|(gt==3)), ((pr==1)|(pr==2)|(pr==3)))
    tc = dice(((gt==1)|(gt==3)),         ((pr==1)|(pr==3)))
    et = dice((gt==3),                   (pr==3))

    rows.append({"id": cid, "dice_WT": wt, "dice_TC": tc, "dice_ET": et})

df_A = pd.DataFrame(rows)
df_A.to_csv(LOGS / "cross_A_2020_on_2024_dice.csv", index=False)
df_A[["dice_WT","dice_TC","dice_ET"]].describe().round(4)

Dice global por caso (A: 2020->2024): 100%|██████████| 203/203 [00:26<00:00,  7.55it/s]

        dice_WT   dice_TC   dice_ET
count  203.0000  203.0000  203.0000
mean     0.7414    0.4426    0.6045
std      0.2416    0.4004    0.3766
min      0.0000    0.0000    0.0000
25%      0.6851    0.0000    0.2809
50%      0.8226    0.4674    0.7270
75%      0.8985    0.8552    0.9313
max      0.9829    1.0000    1.0000

In [6]:
# Analise condicional 1/3 (A): Frequencia de presenca das regioes compostas no GT 2024

presence_rows = []
for cid in tqdm(test_ids_2024, desc="Presenca GT por caso (A)"):
    gt = load_arr(find_seg(case_dir_2024(cid))).astype(np.int16)
    presence_rows.append({
        "id":     cid,
        "has_WT": bool(((gt==1)|(gt==2)|(gt==3)).any()),
        "has_TC": bool(((gt==1)|(gt==3)).any()),
        "has_ET": bool((gt==3).any()),
    })
pres_df_A = pd.DataFrame(presence_rows)
df_full_A = df_A.merge(pres_df_A, on="id")

df_presence_A = pd.DataFrame([
    {"region":     col,
     "n_presente": int(df_full_A[col].sum()),
     "n_total":    len(df_full_A),
     "pct":        100.0 * df_full_A[col].sum() / len(df_full_A)}
    for col in ["has_WT", "has_TC", "has_ET"]
])
df_presence_A.round(2)

Presenca GT por caso (A): 100%|██████████| 203/203 [00:17<00:00, 11.84it/s]

   region  n_presente  n_total     pct
0  has_WT         203      203  100.00
1  has_TC         152      203   74.88
2  has_ET         150      203   73.89

In [7]:
# Analise condicional 2/3 (A): Dice CONDICIONAL - apenas casos com regiao presente no GT

pairs = [("dice_WT","has_WT"), ("dice_TC","has_TC"), ("dice_ET","has_ET")]
df_conditional_A = pd.DataFrame({
    col: df_full_A.loc[df_full_A[has], col].reset_index(drop=True)
    for col, has in pairs
})
df_conditional_A.to_csv(LOGS / "cross_A_2020_on_2024_conditional.csv", index=False)
df_conditional_A.describe().round(4)

        dice_WT   dice_TC   dice_ET
count  203.0000  152.0000  150.0000
mean     0.7414    0.4990    0.5781
std      0.2416    0.3667    0.3349
min      0.0000    0.0000    0.0000
25%      0.6851    0.0671    0.3341
50%      0.8226    0.5986    0.6945
75%      0.8985    0.8505    0.8629
max      0.9829    0.9855    0.9761

In [8]:
# Analise condicional 3/3 (A): Bimodalidade

df_bimodality_A = pd.DataFrame([
    {"region":         col,
     "pct_dice_zero": float((df_full_A[col] == 0.0).mean()) * 100,
     "pct_dice_one":  float((df_full_A[col] >= 0.999).mean()) * 100}
    for col, _ in pairs
])
df_bimodality_A.to_csv(LOGS / "cross_A_2020_on_2024_bimodality.csv", index=False)
df_bimodality_A.round(2)

    region  pct_dice_zero  pct_dice_one
0  dice_WT           4.43          0.00
1  dice_TC          28.08          6.90
2  dice_ET          18.23         17.73

In [9]:
# Metrica 3 (A): Lesion-wise Dice

LW_MIN_SIZE = 50

def lesion_wise_dice(gt_mask: np.ndarray, pr_mask: np.ndarray, min_size: int = LW_MIN_SIZE) -> float:
    structure = np.ones((3, 3, 3), dtype=int)
    if not gt_mask.any() and not pr_mask.any():
        return 1.0
    gt_lab, n_gt = cc_label(gt_mask.astype(bool), structure=structure)
    pr_lab, n_pr = cc_label(pr_mask.astype(bool), structure=structure)
    dice_list = []
    matched_pred = set()
    for g in range(1, n_gt + 1):
        gt_l = (gt_lab == g)
        if gt_l.sum() < min_size:
            continue
        overlap_ids = np.unique(pr_lab[gt_l])
        overlap_ids = overlap_ids[overlap_ids > 0]
        if len(overlap_ids) == 0:
            dice_list.append(0.0)
        else:
            pr_match = np.isin(pr_lab, overlap_ids)
            inter = np.logical_and(gt_l, pr_match).sum()
            denom = gt_l.sum() + pr_match.sum()
            dice_list.append(2.0 * inter / denom if denom > 0 else 0.0)
            matched_pred.update(int(p) for p in overlap_ids)
    for p in range(1, n_pr + 1):
        if p in matched_pred:
            continue
        pr_l = (pr_lab == p)
        if pr_l.sum() < min_size:
            continue
        dice_list.append(0.0)
    return float(np.mean(dice_list)) if dice_list else 1.0


lw_rows = []
for cid in tqdm(test_ids_2024, desc="Lesion-wise Dice por caso (A)"):
    gt = load_arr(find_seg(case_dir_2024(cid))).astype(np.int16)
    pr = load_arr(get_pred_path(PRED_2020_ON_2024, cid)).astype(np.int16)

    gt_wt = (gt==1)|(gt==2)|(gt==3)
    pr_wt = (pr==1)|(pr==2)|(pr==3)
    gt_tc = (gt==1)|(gt==3)
    pr_tc = (pr==1)|(pr==3)
    gt_et = (gt==3)
    pr_et = (pr==3)

    lw_rows.append({
        "id":     cid,
        "lwd_WT": lesion_wise_dice(gt_wt, pr_wt),
        "lwd_TC": lesion_wise_dice(gt_tc, pr_tc),
        "lwd_ET": lesion_wise_dice(gt_et, pr_et),
    })

lw_df_A = pd.DataFrame(lw_rows)
lw_df_A.to_csv(LOGS / "cross_A_2020_on_2024_lwd.csv", index=False)
lw_df_A[["lwd_WT","lwd_TC","lwd_ET"]].describe().round(4)

Lesion-wise Dice por caso (A): 100%|██████████| 203/203 [02:28<00:00,  1.37it/s]

         lwd_WT    lwd_TC    lwd_ET
count  203.0000  203.0000  203.0000
mean     0.5258    0.4111    0.6202
std      0.3036    0.3890    0.3662
min      0.0000    0.0000    0.0000
25%      0.2771    0.0000    0.3372
50%      0.4401    0.3196    0.7302
75%      0.8531    0.8226    1.0000
max      0.9829    1.0000    1.0000

In [10]:
# Direcao B: nnUNet treinado em BraTS2024 -> predito sobre teste BraTS2020 
# Configura env vars apontando para o modelo 2024.

os.environ["nnUNet_raw"]          = str(NNUNET_2024_BASE / "nnUNet_raw")
os.environ["nnUNet_preprocessed"] = str(NNUNET_2024_BASE / "nnUNet_preprocessed")
os.environ["nnUNet_results"]      = str(NNUNET_2024_BASE / "nnUNet_results")

!nnUNetv2_predict -i "{IMAGES_TS_2020}" -o "{PRED_2024_ON_2020}" -d {DATASET_2024_ID} -c 3d_fullres -f 0 -tr nnUNetTrainer_250epochs

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 53 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 53 cases that I would like to predict

Predicting BraTS20_Training_006:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_006

Predicting BraTS20_Training_008:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_008

Predicting BraTS20_Training_014:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_014

Predicting BraTS20_Training_016:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_016

Predicting BraTS20_Training_035:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_035

Predicting BraTS20_Training_042:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_042

Predicting BraTS20_Training_048:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_048

Predicting BraTS20_Training_054:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_054

Predicting BraTS20_Training_056:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_056

Predicting BraTS20_Training_059:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_059

Predicting BraTS20_Training_062:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_062

Predicting BraTS20_Training_064:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_064

Predicting BraTS20_Training_065:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_065

Predicting BraTS20_Training_066:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_066

Predicting BraTS20_Training_077:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_077

Predicting BraTS20_Training_084:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_084

Predicting BraTS20_Training_094:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_094

Predicting BraTS20_Training_096:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_096

Predicting BraTS20_Training_100:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_100

Predicting BraTS20_Training_105:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_105

Predicting BraTS20_Training_106:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_106

Predicting BraTS20_Training_110:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_110

Predicting BraTS20_Training_116:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_116

Predicting BraTS20_Training_119:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_119

Predicting BraTS20_Training_132:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_132

Predicting BraTS20_Training_151:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_151

Predicting BraTS20_Training_153:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_153

Predicting BraTS20_Training_154:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_154

Predicting BraTS20_Training_156:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_156

Predicting BraTS20_Training_159:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_159

Predicting BraTS20_Training_162:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_162

Predicting BraTS20_Training_175:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_175

Predicting BraTS20_Training_182:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_182

Predicting BraTS20_Training_184:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_184

Predicting BraTS20_Training_194:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_194

Predicting BraTS20_Training_201:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_201

Predicting BraTS20_Training_205:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_205

Predicting BraTS20_Training_210:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_210

Predicting BraTS20_Training_213:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_213

Predicting BraTS20_Training_214:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_214

Predicting BraTS20_Training_223:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_223

Predicting BraTS20_Training_227:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_227

Predicting BraTS20_Training_228:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_228

Predicting BraTS20_Training_229:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_229

Predicting BraTS20_Training_271:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_271

Predicting BraTS20_Training_277:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_277

Predicting BraTS20_Training_291:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_291

Predicting BraTS20_Training_292:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_292

Predicting BraTS20_Training_301:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_301

Predicting BraTS20_Training_308:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_308

Predicting BraTS20_Training_313:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_313

Predicting BraTS20_Training_316:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_316

Predicting BraTS20_Training_346:
perform_everything_on_device: True
sending off prediction to background worker for resampling and export
done with BraTS20_Training_346

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:01<00:10,  1.53s/it]
 25%|##5       | 2/8 [00:01<00:04,  1.35it/s]
 38%|###7      | 3/8 [00:02<00:02,  1.75it/s]
 50%|#####     | 4/8 [00:02<00:01,  2.02it/s]
 62%|######2   | 5/8 [00:02<00:01,  2.22it/s]
 75%|#######5  | 6/8 [00:03<00:00,  2.36it/s]
 88%|########7 | 7/8 [00:03<00:00,  2.42it/s]
100%|##########| 8/8 [00:03<00:00,  2.50it/s]
100%|##########| 8/8 [00:03<00:00,  2.01it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.93it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.29it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.70it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.68it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.23it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.89it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.79it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.12it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.23it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.95it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.74it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.85it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.79it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.75it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.78it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.80it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.18it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.74it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.68it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.13it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.23it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.88it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.66it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.50it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.46it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.40it/s]
100%|##########| 8/8 [00:03<00:00,  2.39it/s]
100%|##########| 8/8 [00:03<00:00,  2.57it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.25it/s]
 25%|##5       | 2/8 [00:00<00:02,  2.82it/s]
 38%|###7      | 3/8 [00:01<00:01,  2.60it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.47it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.40it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.36it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.36it/s]
100%|##########| 8/8 [00:03<00:00,  2.39it/s]
100%|##########| 8/8 [00:03<00:00,  2.47it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.61it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.22it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.87it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.73it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.58it/s]
100%|##########| 8/8 [00:02<00:00,  2.72it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.89it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.20it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.88it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.75it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.70it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.89it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.19it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.92it/s]
100%|##########| 4/4 [00:01<00:00,  2.82it/s]
100%|##########| 4/4 [00:01<00:00,  2.98it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.06it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.21it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.95it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.70it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.94it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.18it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.86it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.70it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.62it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.01it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.21it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.82it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.76it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.74it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.97it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.22it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.96it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.19it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.93it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.65it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.89it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.19it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.92it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.81it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.75it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.72it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.70it/s]
100%|##########| 8/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.96it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.18it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.92it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.82it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.70it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.99it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.21it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.88it/s]
100%|##########| 4/4 [00:01<00:00,  2.79it/s]
100%|##########| 4/4 [00:01<00:00,  2.95it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.71it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.22it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.88it/s]
100%|##########| 4/4 [00:01<00:00,  2.80it/s]
100%|##########| 4/4 [00:01<00:00,  2.95it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.93it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.17it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.90it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.80it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.75it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.72it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.70it/s]
100%|##########| 8/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.80it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.26it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.08it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.88it/s]
100%|##########| 4/4 [00:01<00:00,  2.66it/s]
100%|##########| 4/4 [00:01<00:00,  2.82it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.79it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.90it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.71it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.66it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.62it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.61it/s]
100%|##########| 8/8 [00:02<00:00,  2.73it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.91it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.18it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.86it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.74it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.75it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.84it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.67it/s]
100%|##########| 8/8 [00:02<00:00,  2.67it/s]
100%|##########| 8/8 [00:02<00:00,  2.80it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.89it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.28it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.91it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.81it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.67it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.02it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.21it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.88it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.80it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.70it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.78it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.95it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.20it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.92it/s]
100%|##########| 4/4 [00:01<00:00,  2.81it/s]
100%|##########| 4/4 [00:01<00:00,  2.97it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.77it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.02it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.20it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.88it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.75it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.84it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.18it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.87it/s]
100%|##########| 4/4 [00:01<00:00,  2.79it/s]
100%|##########| 4/4 [00:01<00:00,  2.94it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.13it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.24it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.95it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.74it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.72it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.71it/s]
100%|##########| 8/8 [00:02<00:00,  2.70it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.05it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.22it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.95it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.84it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.67it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.67it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.78it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.82it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.18it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.92it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.77it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.07it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.20it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.73it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.03it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.21it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.94it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.74it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.78it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.97it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.20it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.89it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.76it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.68it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.62it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.91it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.25it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.96it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.78it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.74it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.71it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.80it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.03it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.20it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.93it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.83it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.78it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.70it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.79it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|##5       | 1/4 [00:00<00:00,  4.83it/s]
 50%|#####     | 2/4 [00:00<00:00,  3.18it/s]
 75%|#######5  | 3/4 [00:00<00:00,  2.87it/s]
100%|##########| 4/4 [00:01<00:00,  2.79it/s]
100%|##########| 4/4 [00:01<00:00,  2.94it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.74it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.24it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.90it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.80it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.65it/s]
100%|##########| 8/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.78it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.97it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.30it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.92it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.82it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.77it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.70it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.69it/s]
100%|##########| 8/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.81it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.96it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.30it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.92it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.82it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.72it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.24it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.88it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.75it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.63it/s]
100%|##########| 8/8 [00:02<00:00,  2.76it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  5.05it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.29it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.91it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.81it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.75it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.69it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.68it/s]
100%|##########| 8/8 [00:02<00:00,  2.80it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.81it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.26it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.91it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.81it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.72it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.67it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.64it/s]
100%|##########| 8/8 [00:02<00:00,  2.77it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|#2        | 1/8 [00:00<00:01,  4.86it/s]
 25%|##5       | 2/8 [00:00<00:01,  3.19it/s]
 38%|###7      | 3/8 [00:00<00:01,  2.87it/s]
 50%|#####     | 4/8 [00:01<00:01,  2.79it/s]
 62%|######2   | 5/8 [00:01<00:01,  2.71it/s]
 75%|#######5  | 6/8 [00:02<00:00,  2.66it/s]
 88%|########7 | 7/8 [00:02<00:00,  2.66it/s]
100%|##########| 8/8 [00:02<00:00,  2.62it/s]

In [11]:
# Metrica 1 (B): Dice GLOBAL - modelo 2024 sobre teste 2020

rows = []
for cid in tqdm(test_ids_2020, desc="Dice global por caso (B: 2024->2020)"):
    gt = load_arr(find_seg(case_dir_2020(cid))).astype(np.int16)
    gt[gt == 4] = 3  
    pr = load_arr(get_pred_path(PRED_2024_ON_2020, cid)).astype(np.int16)
    pr[pr == 4] = 0  

    wt = dice(((gt==1)|(gt==2)|(gt==3)), ((pr==1)|(pr==2)|(pr==3)))
    tc = dice(((gt==1)|(gt==3)),         ((pr==1)|(pr==3)))
    et = dice((gt==3),                   (pr==3))

    rows.append({"id": cid, "dice_WT": wt, "dice_TC": tc, "dice_ET": et})

df_B = pd.DataFrame(rows)
df_B.to_csv(LOGS / "cross_B_2024_on_2020_dice.csv", index=False)
df_B[["dice_WT","dice_TC","dice_ET"]].describe().round(4)

Dice global por caso (B: 2024->2020): 100%|██████████| 53/53 [00:06<00:00,  8.71it/s]

       dice_WT  dice_TC  dice_ET
count  53.0000  53.0000  53.0000
mean    0.8811   0.7825   0.8127
std     0.0780   0.2997   0.1889
min     0.6594   0.0000   0.0000
25%     0.8319   0.8282   0.7937
50%     0.9062   0.9170   0.8815
75%     0.9381   0.9412   0.9126
max     0.9689   0.9782   0.9574

In [12]:
# Analise condicional 1/3 (B): Frequencia de presenca das regioes compostas no GT 2020

presence_rows = []
for cid in tqdm(test_ids_2020, desc="Presenca GT por caso (B)"):
    gt = load_arr(find_seg(case_dir_2020(cid))).astype(np.int16)
    gt[gt == 4] = 3
    presence_rows.append({
        "id":     cid,
        "has_WT": bool(((gt==1)|(gt==2)|(gt==3)).any()),
        "has_TC": bool(((gt==1)|(gt==3)).any()),
        "has_ET": bool((gt==3).any()),
    })
pres_df_B = pd.DataFrame(presence_rows)
df_full_B = df_B.merge(pres_df_B, on="id")

df_presence_B = pd.DataFrame([
    {"region":     col,
     "n_presente": int(df_full_B[col].sum()),
     "n_total":    len(df_full_B),
     "pct":        100.0 * df_full_B[col].sum() / len(df_full_B)}
    for col in ["has_WT", "has_TC", "has_ET"]
])
df_presence_B.round(2)

Presenca GT por caso (B): 100%|██████████| 53/53 [00:02<00:00, 24.30it/s]

   region  n_presente  n_total    pct
0  has_WT          53       53  100.0
1  has_TC          53       53  100.0
2  has_ET          53       53  100.0

In [13]:
# Analise condicional 2/3 (B): Dice CONDICIONAL

pairs = [("dice_WT","has_WT"), ("dice_TC","has_TC"), ("dice_ET","has_ET")]
df_conditional_B = pd.DataFrame({
    col: df_full_B.loc[df_full_B[has], col].reset_index(drop=True)
    for col, has in pairs
})
df_conditional_B.to_csv(LOGS / "cross_B_2024_on_2020_conditional.csv", index=False)
df_conditional_B.describe().round(4)

       dice_WT  dice_TC  dice_ET
count  53.0000  53.0000  53.0000
mean    0.8811   0.7825   0.8127
std     0.0780   0.2997   0.1889
min     0.6594   0.0000   0.0000
25%     0.8319   0.8282   0.7937
50%     0.9062   0.9170   0.8815
75%     0.9381   0.9412   0.9126
max     0.9689   0.9782   0.9574

In [14]:
# Analise condicional 3/3 (B): Bimodalidade

df_bimodality_B = pd.DataFrame([
    {"region":         col,
     "pct_dice_zero": float((df_full_B[col] == 0.0).mean()) * 100,
     "pct_dice_one":  float((df_full_B[col] >= 0.999).mean()) * 100}
    for col, _ in pairs
])
df_bimodality_B.to_csv(LOGS / "cross_B_2024_on_2020_bimodality.csv", index=False)
df_bimodality_B.round(2)

    region  pct_dice_zero  pct_dice_one
0  dice_WT           0.00           0.0
1  dice_TC           1.89           0.0
2  dice_ET           3.77           0.0

In [15]:
# Metrica 3 (B): Lesion-wise Dice

lw_rows = []
for cid in tqdm(test_ids_2020, desc="Lesion-wise Dice por caso (B)"):
    gt = load_arr(find_seg(case_dir_2020(cid))).astype(np.int16)
    gt[gt == 4] = 3
    pr = load_arr(get_pred_path(PRED_2024_ON_2020, cid)).astype(np.int16)
    pr[pr == 4] = 0 

    gt_wt = (gt==1)|(gt==2)|(gt==3)
    pr_wt = (pr==1)|(pr==2)|(pr==3)
    gt_tc = (gt==1)|(gt==3)
    pr_tc = (pr==1)|(pr==3)
    gt_et = (gt==3)
    pr_et = (pr==3)

    lw_rows.append({
        "id":     cid,
        "lwd_WT": lesion_wise_dice(gt_wt, pr_wt),
        "lwd_TC": lesion_wise_dice(gt_tc, pr_tc),
        "lwd_ET": lesion_wise_dice(gt_et, pr_et),
    })

lw_df_B = pd.DataFrame(lw_rows)
lw_df_B.to_csv(LOGS / "cross_B_2024_on_2020_lwd.csv", index=False)
lw_df_B[["lwd_WT","lwd_TC","lwd_ET"]].describe().round(4)

Lesion-wise Dice por caso (B): 100%|██████████| 53/53 [00:49<00:00,  1.07it/s]

        lwd_WT   lwd_TC   lwd_ET
count  53.0000  53.0000  53.0000
mean    0.6623   0.7462   0.7512
std     0.2819   0.3079   0.2420
min     0.0758   0.0000   0.0000
25%     0.4415   0.6562   0.6931
50%     0.7938   0.9076   0.8628
75%     0.9175   0.9387   0.9115
max     0.9689   0.9782   0.9574

In [16]:
# Tabela consolidada cross-dataset (medias) - apenas WT, TC, ET

summary = pd.DataFrame([
    {"direcao": "2020 -> 2024",
     "Dice WT": df_A["dice_WT"].mean(),  "Dice TC": df_A["dice_TC"].mean(),  "Dice ET": df_A["dice_ET"].mean(),
     "LWD WT":  lw_df_A["lwd_WT"].mean(), "LWD TC":  lw_df_A["lwd_TC"].mean(), "LWD ET":  lw_df_A["lwd_ET"].mean()},
    {"direcao": "2024 -> 2020",
     "Dice WT": df_B["dice_WT"].mean(),  "Dice TC": df_B["dice_TC"].mean(),  "Dice ET": df_B["dice_ET"].mean(),
     "LWD WT":  lw_df_B["lwd_WT"].mean(), "LWD TC":  lw_df_B["lwd_TC"].mean(), "LWD ET":  lw_df_B["lwd_ET"].mean()},
])
summary.to_csv(LOGS / "cross_summary_nnUNet.csv", index=False)
summary.round(4)

        direcao  Dice WT  Dice TC  Dice ET  LWD WT  LWD TC  LWD ET
0  2020 -> 2024   0.7414   0.4426   0.6045  0.5258  0.4111  0.6202
1  2024 -> 2020   0.8811   0.7825   0.8127  0.6623  0.7462  0.7512